config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users

  get     'cups'              => "cups#index",      as: :cups
  post    'cups'              => "cups#create"
  get     'cups/new'          => "cups#new",        as: :new_cup
  get     'cups/:cup_id/edit' => "cups#edit",       as: :edit_cup
  get     'cups/:cup_id'      => "cups#show",       as: :cup
  patch   'cups/:cup_id'      => "cups#update"
  put     'cups/:cup_id'      => "cups#update"
  delete  'cups/:cup_id'      => "cups#destroy",    as: :delete_cup

  get     'teams/:cup_id'       => "teams#index",     as: :teams
  post    'teams/:cup_id'       => "teams#create"
  get     'teams/new/:cup_id'   => "teams#new",       as: :new_team
  get     'teams/:team_id/edit' => "teams#edit",      as: :edit_team
  get     'teams/:team_id/show' => "teams#show",      as: :team
  patch   'teams/:team_id/show' => "teams#update"
  put     'teams/:team_id/show' => "teams#update"
  delete  'teams/:team_id'      => "teams#destroy",   as: :delete_team

  get     'matches/:cup_id'             => "matches#index",   as: :matches
  post    'matches/:cup_id'             => "matches#create"
  get     'matches/new/:cup_id'         => "matches#new",     as: :new_match
  get     'matches/:match_id/edit'      => "matches#edit",    as: :edit_match
  get     'matches/:match_id/show'      => "matches#show",    as: :match
  patch   'matches/:match_id/show'      => "matches#update"
  put     'matches/:match_id/show'      => "matches#update"
  delete  'matches/:match_id'           => "matches#destroy", as: :delete_match

  get     'predictions/:cup_id'             => "predictions#index",   as: :predictions
  post    'predictions/:cup_id'             => "predictions#create"
  get     'predictions/new/:cup_id'         => "predictions#new",     as: :new_prediction
  get     'predictions/:prediction_id/edit' => "predictions#edit",    as: :edit_prediction
  get     'predictions/:prediction_id/show' => "predictions#show",    as: :prediction
  patch   'predictions/:prediction_id/show' => "predictions#update"
  put     'predictions/:prediction_id/show' => "predictions#update"
  delete  'predictions/:prediction_id'      => "predictions#destroy", as: :delete_prediction

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  root 'cups#index'

end

app/models/prediction.rb
class Prediction < ActiveRecord::Base
  belongs_to :match
  belongs_to :user
  belongs_to :cup

  validate :allow_update_reward_only

  validates :match_id, uniqueness: { scope: :user_id, message: "one prediction per match for each user" }

  after_save :update_score

  def update_score
    Score.find_or_create_by(user: user, cup: cup)
  end

  def allow_update_reward_only
    if id_changed? || match_id_changed? || user_id_changed? || cup_id_changed? || mainscore1_changed? || mainscore2_changed?
      validate_match
    end
  end

  def validate_match
    errors.add(:match, ' started !!!') if match.started? && !APP_CONFIG["skip_validation"]
    errors.add(:match, ' is in knockout stage!!! Must chose ONE winner!!!') if match.knockout? && (mainscore1 == mainscore2)
  end

  def locked?
    match.started? && !APP_CONFIG["skip_validation"]
  end

  def open?
    !locked?
  end

  def closed?
    match.closed?
  end

  def score
    match.knockout? ? (win? ? 2 : 0) : (win? ? 2 : (subwin? ? 1 : 0))
  end

  def mainscores
    "#{mainscore1} - #{mainscore2}"
  end

  def win?
    if match.knockout?
      if match.special_final?
        closed? && (
        ((match.mainscore1 - match.prior1 > match.mainscore2 - match.prior2) && (mainscore1 > mainscore2)) ||
        ((match.mainscore1 - match.prior1 < match.mainscore2 - match.prior2) && (mainscore1 < mainscore2)) ||
        (!match.subscore1.nil? && !match.subscore2.nil? && (match.subscore1 - match.prior1 > match.subscore2 - match.prior2) && (mainscore1 > mainscore2)) ||
        (!match.subscore1.nil? && !match.subscore2.nil? && (match.subscore1 - match.prior1 < match.subscore2 - match.prior2) && (mainscore1 < mainscore2)) ||
        (!match.penscore1.nil? && !match.penscore2.nil? && (match.penscore1 - match.prior1 > match.penscore2 - match.prior2) && (mainscore1 > mainscore2)) ||
        (!match.penscore1.nil? && !match.penscore2.nil? && (match.penscore1 - match.prior1 < match.penscore2 - match.prior2) && (mainscore1 < mainscore2)))
      else
        closed? && (
        ((match.mainscore1 - match.prior1 > match.mainscore2 - match.prior2) && (mainscore1 > mainscore2)) ||
        ((match.mainscore1 - match.prior1 < match.mainscore2 - match.prior2) && (mainscore1 < mainscore2)))
      end
    else
      closed? && ((match.mainscore1 == mainscore1) && (match.mainscore2 == mainscore2))
    end
  end

  def subwin?
    closed? && (win? ? false :
      ( ((match.mainscore1 == match.mainscore2) && (mainscore1 == mainscore2)) ||
        ((match.mainscore1 >  match.mainscore2) && (mainscore1 >  mainscore2)) ||
        ((match.mainscore1 <  match.mainscore2) && (mainscore1 <  mainscore2)) ))
  end

  def halfwin?
    if match.knockout?
      closed? && win? && (((match.mainscore1 - match.prior1) - (match.mainscore2 - match.prior2)).abs == 0.25)
    else
      false
    end
  end

  def halflose?
    if match.knockout?
      closed? && !win? && (((match.mainscore1 - match.prior1) - (match.mainscore2 - match.prior2)).abs == 0.25)
    else
      false
    end
  end

  def winner_team
    (mainscore1 > mainscore2) ? match.team1 : ((mainscore1 < mainscore2) ? match.team2 : nil)
  end
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  load_and_authorize_resource param_method: :prediction_params
  before_action :set_prediction, only: [:show, :edit, :update, :destroy]
  before_action :set_cup, only: [:index, :create, :new]

  def index
    @predictions = current_user.predictions.where(cup_id: @cup.id).order(:match_id)
  end

  def show
    @cup = @prediction.cup
  end

  def new
    @prediction = Prediction.new(
      user_id: current_user.id,
      cup_id: @cup.id
    )
  end

  def edit; end

  def create
    @prediction = Prediction.new(prediction_params.merge(
      user_id: current_user.id,
      cup_id: @cup.id
    ))

    if @prediction.save
      redirect_to @prediction, notice: 'Prediction was successfully created.'
    else
      render :new
    end
  end

  def update
    if @prediction.update(prediction_params)
      redirect_to @prediction, notice: 'Prediction was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @prediction.destroy
    redirect_to predictions_path(cup_id: @prediction.cup_id), 
      notice: 'Prediction was successfully destroyed.'
  end

  private
    def set_prediction
      @prediction = Prediction.find(params[:prediction_id])
    end

    def set_cup
      @cup = Cup.find(params[:cup_id])
    end

    def prediction_params
      params.require(:prediction).permit(:match_id, :mainscore1, :mainscore2)
    end
end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.slim
= form_for(@prediction) do |f|
  - if @prediction.errors.any?
    div#error_explanation
      h2 = pluralize(@prediction.errors.count, "error") 
      | prohibited this prediction from being saved:
      ul
      - @prediction.errors.full_messages.each do |message|
        li = message

  fieldset.col-xs-6
    div.field.form-group
      = f.label :match_id, class: "form-left"
      = f.collection_select :match_id, predicable_matches(current_user), :id, :name, class: "form-right"
    #team1score.field.form-group
      = f.label :mainscore1, id: "team1_name", class: "form-left"
      = f.number_field :mainscore1, class: "form-right"
    #team2score.field.form-group
      = f.label :mainscore2, id: "team2_name", class: "form-left"
      = f.number_field :mainscore2, class: "form-right"
    #teamselected.field
      label.form-left Choose team
      select id="teamoption" class="form-right"
    br
    div.field.form-group
      div.actions
        = f.submit 'Submit', class: 'btn btn-primary form-left', data: { disable_with: "Please wait..." }

javascript:
  var predicable_matches = #{{predicable_matches(current_user).map{|m| {"id"=>m.id, "team1_id"=>m.team1_id, "team2_id"=>m.team2_id, "knockout"=>m.knockout}}.to_json}};
  var playing_teams = #{{Team.where(status: true).map{|t| {"id"=>t.id, "name"=>t.name}}.to_json}};
  $('#prediction_match_id').change(function(){
    $selected_value=$('#prediction_match_id option:selected').val();
    $match = predicable_matches.find(x => x.id == $selected_value);
    $team1_name = playing_teams.find(x => x.id == $match.team1_id).name;
    $('#team1_name').text($team1_name);
    $team2_name = playing_teams.find(x => x.id == $match.team2_id).name;
    $('#team2_name').text($team2_name);
    $('#teamoption').empty();
    $('#teamoption').append(new Option($team1_name, 1, true, true));
    $('#teamoption').append(new Option($team2_name, 2, false, false));
    if ($match["knockout"] == true) {
      $('#prediction_mainscore1').val(1);
      $('#prediction_mainscore2').val(0);
      $('#team1score').hide();
      $('#team2score').hide();
      $('#teamselected').show();
    }
    else {
      $('#team1score').show();
      $('#team2score').show();
      $('#teamselected').hide();
    }
  });
  $('#teamoption').change(function(){
    $selected_value=$('#teamoption option:selected').val();
    if ($selected_value == 1) {
      $('#prediction_mainscore1').val(1);
      $('#prediction_mainscore2').val(0);
    }
    else {
      $('#prediction_mainscore1').val(0);
      $('#prediction_mainscore2').val(1);
    }
  });
  $('#prediction_match_id').change();

app/views/predictions/edit.html.slim
h1 Editing Prediction

= render 'form'

div.col-xs-12
  hr
  - if can?(:create, Prediction)
    = link_to 'New prediction', new_prediction_path(cup_id: @prediction.cup_id), class: "btn btn-primary"
    | |
  = link_to 'Back', predictions_path(cup_id: @prediction.cup_id), class: "btn btn-primary"

app/views/predictions/index.html.slim
.container
  h1 Listing Predictions

  - if @predictions.count == 0
    p You don't have any prediction yet !!!
  -else
    div.panel.panel-default
      table.table.table-condensed
        thead
          tr
            th.col-xs-1  #
            th.col-xs-3  Match
            th.col-xs-1  Result
            th.col-xs-1  Prediction
            th.col-xs-1  Score
            th.col-xs-1  Updated at
            th.col-xs-1  colspan="3"

    div.div-table-content
      table.table.table-hover
        tbody
          - @predictions.each_with_index do |prediction, index|
            tr.clickable href="#{can?(:edit, prediction) ? edit_prediction_path(prediction) : prediction_path(prediction)}"
              td.col-xs-1  = index + 1
              td.col-xs-3  = render "shared/match_name", match: prediction.match
              td.col-xs-1  = prediction.closed? ? "#{prediction.match.mainscore1} - #{prediction.match.mainscore2}" : "Not available"
              - if prediction.match.knockout?
                td.col-xs-1 = prediction.winner_team.name
              - else
                td.col-xs-1 = prediction.mainscores
              = render "shared/prediction_score", prediction: prediction
              td.col-xs-1  = prediction.updated_at.to_s(:match)
              td.col-xs-1.text-right
                - if can?(:destroy, prediction)
                  = link_to 'Destroy', delete_prediction_path(prediction), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs btn-one-col'
          td
          td
          td
          td
          td.btn-danger = current_user.get_score(@cup)

  div.col-xs-12
    hr
    - if can?(:create, Prediction)
      = link_to 'New Prediction', new_prediction_path(cup_id: @cup.id), class: 'btn btn-primary'

app/views/predictions/new.html.slim
h1 New Prediction

= render 'form'

div.col-xs-12
  hr
  = link_to 'Back', predictions_path(cup_id: @cup.id), class: 'btn btn-primary'

app/views/predictions/show.html.slim
.container
  table.table
    tr
      th  Match
      th= render "shared/match_name", match: @prediction.match

    tr
      td User
      td= @prediction.user.name

    tr
      - if @prediction.match.knockout?
        td Prediction team
        td= @prediction.winner_team.name
      - else
        td Main score
        td= @prediction.mainscores

  div.col-xs-12
    hr
    - if can?(:edit, @prediction)
      = link_to 'Edit', edit_prediction_path(@prediction), class: "btn btn-primary"
      | |
    = link_to 'Back', predictions_path(cup_id: @prediction.cup_id), class: "btn btn-primary btn-warning"