config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users

  get     'cups'              => "cups#index",      as: :cups
  post    'cups'              => "cups#create"
  get     'cups/new'          => "cups#new",        as: :new_cup
  get     'cups/:cup_id/edit' => "cups#edit",       as: :edit_cup
  get     'cups/:cup_id'      => "cups#show",       as: :cup
  patch   'cups/:cup_id'      => "cups#update"
  put     'cups/:cup_id'      => "cups#update"
  delete  'cups/:cup_id'      => "cups#destroy",    as: :delete_cup

  get     'teams/:cup_id'       => "teams#index",     as: :teams
  post    'teams/:cup_id'       => "teams#create"
  get     'teams/new/:cup_id'   => "teams#new",       as: :new_team
  get     'teams/:team_id/edit' => "teams#edit",      as: :edit_team
  get     'teams/:team_id/show' => "teams#show",      as: :team
  patch   'teams/:team_id/show' => "teams#update"
  put     'teams/:team_id/show' => "teams#update"
  delete  'teams/:team_id'      => "teams#destroy",   as: :delete_team

  get     'matches/:cup_id'             => "matches#index",   as: :matches
  post    'matches/:cup_id'             => "matches#create"
  get     'matches/new/:cup_id'         => "matches#new",     as: :new_match
  get     'matches/:match_id/edit'      => "matches#edit",    as: :edit_match
  get     'matches/:match_id/show'      => "matches#show",    as: :match
  patch   'matches/:match_id/show'      => "matches#update"
  put     'matches/:match_id/show'      => "matches#update"
  delete  'matches/:match_id'           => "matches#destroy", as: :delete_match

  get     'predictions/:cup_id'             => "predictions#index",   as: :predictions
  post    'predictions/:cup_id'             => "predictions#create"
  get     'predictions/new/:cup_id'         => "predictions#new",     as: :new_prediction
  get     'predictions/:prediction_id/edit' => "predictions#edit",    as: :edit_prediction
  get     'predictions/:prediction_id/show' => "predictions#show",    as: :prediction
  patch   'predictions/:prediction_id/show' => "predictions#update"
  put     'predictions/:prediction_id/show' => "predictions#update"
  delete  'predictions/:prediction_id'      => "predictions#destroy", as: :delete_prediction

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  root 'cups#index'

end

app/models/cup.rb
class Cup < ActiveRecord::Base
  has_many :matches, dependent: :destroy
  has_many :teams, dependent: :destroy

  def total_matches_count
    matches.count
  end

  def played_matches
    matches.where(status: true)
  end

  def played_matches_count
    played_matches.count
  end

  def on_going
    start_date <= Date.today && end_date >= Date.today
  end

  def update_result
    matches.includes([:team1, :team2]).select{|match| (match.started? && !match.closed?)}.each do |m|
      m.update_result
    end
  end

  def active_users
    User.select{|u| !u.inactive?(self)}
  end

  def active_users_count
    active_users.count
  end
end

app/controllers/cups_controller.rb
class CupsController < ApplicationController
  load_and_authorize_resource cup_method: :cup_params
  before_action :set_cup, only: [:show, :edit, :update, :destroy]

  def index
    @cups = Cup.all
  end

  def show
    if @cup.result_id != 0
      @cup.update_result
    end
    @nextmatches = @cup.matches.where("time >= ?", Time.now).order(time: :asc).first(5)
    @prematches = @cup.matches.where("time <= ?", Time.now).reorder(time: :desc).first(5)
  end

  def new
    @cup = Cup.new
  end

  def edit
  end

  def create
    @cup = Cup.new(cup_params)

    if @cup.save
      redirect_to @cup, notice: 'Cup was successfully created.'
    else
      render :new
    end
  end

  def update
    if @cup.update(cup_params)
      redirect_to @cup, notice: 'Cup was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @cup.destroy
    redirect_to cups_url, notice: 'Cup was successfully destroyed.'
  end

  private
    def set_cup
      @cup = Cup.find(params[:cup_id])
    end

    def cup_params
      params.require(:cup).permit(:name, :host, :logo, :start_date, :end_date, :is_league, :result_id, :reward_percent, :save_reward)
    end
end

app/views/cups/_form.html.slim
div.col-xs-6
  = form_for(@cup) do |f|
    - if @cup.errors.any?
      div#error_explanation
        h2= pluralize(@cup.errors.count, "error")
        | prohibited this cup from being saved:

        ul
        - @cup.errors.full_messages.each do |message|
          li= message

    div.field.form-group
      = f.label :name, class: "form-left"
      = f.text_field :name, class: "form-right"
    div.field.form-group
      = f.label :host, class: "form-left"
      = f.text_field :host, class: "form-right"
    div.field.form-group
      = f.label :logo, class: "form-left"
      = f.text_field :logo, class: "form-right"
    div.field.form-group
      = f.label :start_date, class: "form-left"
      = f.date_select :start_date, class: "form-right"
    div.field.form-group
      = f.label :end_date, class: "form-left"
      = f.date_select :end_date, class: "form-right"
    div.field.form-group
      = f.label "Type", class: "form-left"
      = f.select :is_league, [['Cup', false], ['League', true]], class: "form-right"
    div.field.form-group
      = f.label :result_id, class: "form-left"
      = f.number_field :result_id, class: "form-right"
    div.field.form-group
      = f.label :reward_percent, class: "form-left"
      = f.number_field :reward_percent, class: "form-right", step: 0.1
    div.field.form-group
      = f.label :save_reward, class: "form-left"
      = f.number_field :save_reward, class: "form-right"
    div.field.form-group
      div.actions
        = f.submit "Submit", class: "form-left btn btn-primary"

app/views/cups/edit.html.slim
h1 Editing Cup

= render 'form'

div.col-xs-12
  hr
  = link_to 'Show', @cup, class: "btn btn-primary"
  |  | 
  = link_to 'Back', cups_path, class: "btn btn-primary"

app/views/cups/index.html.slim
.container
  h1 Listing Cups
  div.panel.panel-default
    table.table.table-condensed
      thead
        tr
          th.col-xs-1 #
          th.col-xs-5 Cup
          th.col-xs-1 Logo
          th.col-xs-3 Start Time
          th.col-xs-3 End Time

  div.div-table-content
    table.table.table-hover.table-condensed
      tbody
        - @cups.each_with_index do |cup, index|
          tr.clickable href="#{cup_path(cup)}"
            td.col-xs-1 = index+1
            td.col-xs-5 = cup.name
            td.col-xs-1 = image_tag(cup.logo, class: "flag-icon")
            td.col-xs-3 = cup.start_date
            td.col-xs-3 = cup.end_date
              - if can?(:destroy, cup)
                = link_to 'Destroy', cup, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger btn-one-col'
              - if can?(:edit, cup)
                = link_to 'Edit', edit_cup_path(cup), class: 'btn btn-xs btn-warning btn-one-col btn-enabled'

  hr

  - if can?(:create, Cup)
    = link_to 'New Cup', new_cup_path, class: "btn btn-primary"

app/views/cups/new.html.slim
h1 New Cup

= render 'form'

div.col-xs-12
  hr
  = link_to 'Back', cups_path, class: "btn btn-primary"

app/views/cups/show.html.slim
h2 Cup information

table.table
  tr
    th.col-xs-4 Name 
    th.col-xs-4= @cup.name
  tr
    td Host
    td= @cup.host
  tr
    td Logo
    td= image_tag(@cup.logo, class: "flag-icon")
  tr
    td Start date
    td= @cup.start_date
  tr
    td End date
    td= @cup.end_date
  tr
    td Type
    td= @cup.is_league? ? "League" : "Cup"

hr

- if @nextmatches.count > 0
  div.panel.panel-default
    table.table.table-cond:wensed
      thead
        tr
          th.col-xs-3 Next Match(es)
          th.col-xs-3 Time
          th.col-xs-3 Bet Priority
          th.col-xs-3 Your Prediction
  div.div-table-content
    table.table.table-hover.table-condensed
      tbody
        - @nextmatches.each do |match|
          tr.clickable href="#{match_path(match.id)}"
            td.col-xs-3 = render "shared/match_name", match: match
            td.col-xs-3 = match.time.to_s(:match)
            td.col-xs-3 = match.priorities
            - if match.prediction_of(@current_user)
              - if match.knockout?
                td.col-xs-3 = match.prediction_of(@current_user).winner_team.name
              - else
                td.col-xs-3 = match.prediction_of(@current_user).mainscores
            - else
              td.col-xs-3 Not available

- if @prematches.count > 0
  div.panel.panel-default
    table.table.table-cond:wensed
      thead
        tr
          th.col-xs-2 Previous Match(es)
          th.col-xs-1 Time
          th.col-xs-1 Status
          th.col-xs-1 Score
          th.col-xs-2 Prediction winner(s)
  div.div-table-content
    table.table.table-hover.table-condensed
      tbody
        - @prematches.each do |match|
          tr.clickable href="#{match_path(match.id)}"
            td.col-xs-2 = render "shared/match_name", match: match
            td.col-xs-1 = match.time.to_s(:match)
            td.col-xs-1 = match.human_status
            td.col-xs-1 = match.fullscores
            td.col-xs-2 = match.prediction_winners_names

- if can?(:edit, @cup)
  = link_to 'Edit', edit_cup_path(@cup), class: "btn btn-primary"
  |  | 
= link_to 'Back', cups_path, class: "btn btn-primary"