config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  devise_for :users

  get     'cups'              => "cups#index",      as: :cups
  post    'cups'              => "cups#create"
  get     'cups/new'          => "cups#new",        as: :new_cup
  get     'cups/:cup_id/edit' => "cups#edit",       as: :edit_cup
  get     'cups/:cup_id'      => "cups#show",       as: :cup
  patch   'cups/:cup_id'      => "cups#update"
  put     'cups/:cup_id'      => "cups#update"
  delete  'cups/:cup_id'      => "cups#destroy",    as: :delete_cup

  get     'teams/:cup_id'       => "teams#index",     as: :teams
  post    'teams/:cup_id'       => "teams#create"
  get     'teams/new/:cup_id'   => "teams#new",       as: :new_team
  get     'teams/:team_id/edit' => "teams#edit",      as: :edit_team
  get     'teams/:team_id/show' => "teams#show",      as: :team
  patch   'teams/:team_id/show' => "teams#update"
  put     'teams/:team_id/show' => "teams#update"
  delete  'teams/:team_id'      => "teams#destroy",   as: :delete_team

  get     'matches/:cup_id'             => "matches#index",   as: :matches
  post    'matches/:cup_id'             => "matches#create"
  get     'matches/new/:cup_id'         => "matches#new",     as: :new_match
  get     'matches/:match_id/edit'      => "matches#edit",    as: :edit_match
  get     'matches/:match_id/show'      => "matches#show",    as: :match
  patch   'matches/:match_id/show'      => "matches#update"
  put     'matches/:match_id/show'      => "matches#update"
  delete  'matches/:match_id'           => "matches#destroy", as: :delete_match

  get     'predictions/:cup_id'             => "predictions#index",   as: :predictions
  post    'predictions/:cup_id'             => "predictions#create"
  get     'predictions/new/:cup_id'         => "predictions#new",     as: :new_prediction
  get     'predictions/:prediction_id/edit' => "predictions#edit",    as: :edit_prediction
  get     'predictions/:prediction_id/show' => "predictions#show",    as: :prediction
  patch   'predictions/:prediction_id/show' => "predictions#update"
  put     'predictions/:prediction_id/show' => "predictions#update"
  delete  'predictions/:prediction_id'      => "predictions#destroy", as: :delete_prediction

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end

  root 'cups#index'

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :team1, class_name: "Team", foreign_key: "team1_id"
  belongs_to :team2, class_name: "Team", foreign_key: "team2_id"
  has_many :predictions
  belongs_to :cup

  default_scope { order(:time) }

  after_save :update_score, if: -> { closed? }

  def prediction_of(user)
    predictions.find_by(user: user)
  end

  def name
    team1.name + ((prior1.nil? || prior1== 0) ? '' : "(-"+prior1.to_s+")") + ' vs ' + team2.name + ((prior2.nil? || prior2 == 0) ? '' : "(-"+prior2.to_s+")") + " (#{time.to_s(:match)})"
  end

  def short_name
    team1.name + ' vs ' + team2.name
  end

  def mainscores
    "#{mainscore1} - #{mainscore2}"
  end

  def subscores
    "#{subscore1} - #{subscore2}"
  end

  def fullscores
    if !subscore1.nil? && !subscore2.nil?
      if !penscore1.nil? && !penscore2.nil?
        subscores + " (#{penscore1} - #{penscore2})"
      else
        subscores
      end
    else
      mainscores
    end
  end

  def priorities
    if !knockout?
      "-"
    else 
      if !prior1.nil? && prior1 > 0
        "#{team1.name} -#{prior1} ~> #{rates}"
      else 
        if !prior2.nil? && prior2 > 0 
          "#{team2.name} -#{prior2} ~> #{rates}"
        else
          "- ~> #{rates}"
        end
      end
    end
  end

  def rates
    if knockout?
      "LPC: #{team1.name}(#{predictions.select{|p| p.winner_team == team1}.count}) - (#{predictions.select{|p| p.winner_team == team2}.count})#{team2.name}"
    else
      ""
    end
  end

  def winner
    if closed?
      if !subscore1.nil? && !subscore2.nil? && !penscore1.nil? && !penscore2.nil?
        subscore1 > subscore2 ? team1 :
        subscore1 < subscore2 ? team2 :
        penscore1 > penscore2 ? team1 :
        penscore1 < penscore2 ? team2 : nil
      else
        if !subscore1.nil? && !subscore2.nil?
          subscore1 > subscore2 ? team1 :
          subscore1 < subscore2 ? team2 : nil
        else
          mainscore1 > mainscore2 ? team1 :
          mainscore1 < mainscore2 ? team2 : nil
        end
      end
    end
  end

  def looser
    if closed?
      if !subscore1.nil? && !subscore2.nil? && !penscore1.nil? && !penscore2.nil?
        subscore1 > subscore2 ? team2 :
        subscore1 < subscore2 ? team1 :
        penscore1 > penscore2 ? team2 :
        penscore1 < penscore2 ? team1 : nil
      else
        if !subscore1.nil? && !subscore2.nil?
          subscore1 > subscore2 ? team2 :
          subscore1 < subscore2 ? team1 : nil
        else
          mainscore1 > mainscore2 ? team2 :
          mainscore1 < mainscore2 ? team1 : nil
        end
      end
    end
  end

  def prediction_winners
    if knockout?
      User.where(id: predictions.select{|p| p.win?}.map(&:user_id))
    else
      User.where(id: Prediction.where(match: self, mainscore1: mainscore1, mainscore2: mainscore2).map(&:user_id))
    end
  end

  def prediction_winners_count
    prediction_winners.count
  end

  def prediction_winners_names
    prediction_winners.map(&:name).join(", ")
  end

  def equal?
    closed? && (mainscore1 == mainscore2) 
  end

  def started?
    Time.now >= time
  end

  def closed?
    status == true
  end

  def human_status
    closed? ? 'Finished' : started? ? 'Started' : ''
  end

  def update_score
    update_teams_score
    update_predictions_reward
    update_users_score_reward
  end

  def update_teams_score
    if !knockout?
      team1.update_score
      team2.update_score
      if team1.played_matches.count == 3 && !cup.is_league?
        team1.update_status
      end
      if team2.played_matches.count == 3 && !cup.is_league?
        team2.update_status
      end
    else
      if !cup.is_league?
        winner.update_attributes(status: true)
        looser.update_attributes(status: false)
      end
    end
  end

  def update_predictions_reward
    if knockout?
      if prediction_winners_count == 0
        if cup.is_league?
          predictions.all.each do |prediction|
            prediction.update_attributes(reward: fee)
          end
        else
          cup.update_attributes(save_reward: fee*predictions.count)
          predictions.all.each do |prediction|
            prediction.update_attributes(reward: 0)
          end
        end
      else
        predictions.all.each do |prediction|
          if prediction.halfwin?
            prediction.update_attributes(reward: ((fee*predictions.count/2+cup.save_reward)/prediction_winners_count).round + fee/2)  
          elsif prediction.win?
            prediction.update_attributes(reward: ((fee*predictions.count+cup.save_reward)/prediction_winners_count).round)
          elsif prediction.halflose?
            prediction.update_attributes(reward: fee/2)
          else
            prediction.update_attributes(reward: 0)
          end
        end
        cup.update_attributes(save_reward: 0)
      end
    else
      predictions.all.each do |prediction|
        if prediction.win?
          prediction.update_attributes(reward: (cup.reward_percent*fee*valid_users_count/prediction_winners_count).round)
        else
          prediction.update_attributes(reward: 0)
        end
      end
    end
  end

  def update_users_score_reward
    Score.all.each do |score|
      score.update_score_reward
    end
  end

  def update_result
    require 'net/http'
    if team1.name == "South Korea"
      home_team_name = "Korea Republic"
    else
      home_team_name = team1.name
    end
    if team2.name == "South Korea"
      away_team_name = "Korea Republic"
    else
      away_team_name = team2.name
    end
    uri = URI.parse("http://api.football-data.org/v2/competitions/"+cup.result_id.to_s+"/matches?dateFrom="+Date.yesterday.strftime("%Y-%m-%d")+"&dateTo="+Date.tomorrow.strftime("%Y-%m-%d"))
    http = Net::HTTP.new(uri.host, uri.port).start
    request = Net::HTTP::Get.new(uri.request_uri, {"X-Auth-Token"=>ENV['PG_API_KEY']})
    resp = http.request(request)
    if resp.kind_of? Net::HTTPSuccess
      data = JSON.parse(resp.body)
      match_results = data['matches'].select{|m| (m['homeTeam']['name'] == home_team_name && m['awayTeam']['name'] == away_team_name)}
      if match_results.count > 0
        last_m = match_results.last
        ms1 = last_m['score']['fullTime']['homeTeam'].nil? ? 0 : last_m['score']['fullTime']['homeTeam'] - (last_m['score']['extraTime']['homeTeam'].nil? ? 0 : last_m['score']['extraTime']['homeTeam']) - (last_m['score']['penalties']['homeTeam'].nil? ? 0 : last_m['score']['penalties']['homeTeam'])
        ms2 = last_m['score']['fullTime']['awayTeam'].nil? ? 0 : last_m['score']['fullTime']['awayTeam'] - (last_m['score']['extraTime']['awayTeam'].nil? ? 0 : last_m['score']['extraTime']['awayTeam']) - (last_m['score']['penalties']['awayTeam'].nil? ? 0 : last_m['score']['penalties']['awayTeam'])
        ss1 = last_m['score']['extraTime']['homeTeam'].nil? ? nil : (ms1 + last_m['score']['extraTime']['homeTeam'])
        ss2 = last_m['score']['extraTime']['awayTeam'].nil? ? nil : (ms2 + last_m['score']['extraTime']['awayTeam'])
        if last_m['status'] == 'IN_PLAY'
          update_attributes(mainscore1: ms1, mainscore2: ms2, subscore1: ss1, subscore2: ss2, penscore1: match_results.last['score']['penalties']['homeTeam'], penscore2: match_results.last['score']['penalties']['awayTeam'], status: false)
        end
        if last_m['status'] == 'FINISHED'
          update_attributes(mainscore1: ms1, mainscore2: ms2, subscore1: ss1, subscore2: ss2, penscore1: match_results.last['score']['penalties']['homeTeam'], penscore2: match_results.last['score']['penalties']['awayTeam'], status: true)
        end
      end
    end
  end

  def valid_users
    cup.active_users.select{|u| u.predictions_of_cup(cup).first.match.id <= id}
  end

  def valid_users_count
    valid_users.count
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  load_and_authorize_resource param_method: :match_params
  before_action :set_match, only: [:show, :edit, :update, :destroy]
  before_action :set_cup, only: [:index, :create, :new]

  def index
    if @cup.result_id != 0
      @cup.update_result
    end
    @matches = @cup.matches.order(:time)
  end

  def show
    @cup = @match.cup
  end

  def new
    @match = Match.new(cup_id: @cup.id)
  end

  def edit
  end

  def create
    @match = Match.new(match_params.merge(cup_id: @cup.id))

    if @match.save
      redirect_to @match, notice: 'Match was successfully created.'
    else
      render :new
    end
  end

  def update
    if @match.update(match_params)
      redirect_to @match, notice: 'Match was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @match.destroy
    redirect_to matches_path(cup_id: @match.cup_id), 
      notice: 'Match was successfully destroyed.'
  end

  private
    def set_match
      @match = Match.find(params[:match_id])
    end

    def set_cup
      @cup = Cup.find(params[:cup_id])
    end

    def match_params
      params.require(:match).permit(
        :team1_id,
        :team2_id,
        :time,
        :status,
        :mainscore1,
        :mainscore2,
        :subscore1,
        :subscore2,
        :penscore1,
        :penscore2,
        :knockout,
        :prior1,
        :prior2,
        :fee,
        :special_final
      )
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.slim
= form_for(@match) do |f|
  - if @match.errors.any?
    div#error_explanation
      h2 = pluralize(@match.errors.count, "error")
      | prohibited this match from being saved:

      ul
      - @match.errors.full_messages.each do |message|
        li= message

  fieldset.col-xs-6
    div.field.form-group
      = f.label :team1_id, class: "form-left"
      = f.collection_select :team1_id, @match.cup.teams.where(status: true), :id, :name, class: "form-right"
    div.field.form-group
      = f.label :team2_id, class: "form-left"
      = f.collection_select :team2_id, @match.cup.teams.where(status: true), :id, :name, class: "form-right"
    div.field.form-group
      = f.label :time, class: "form-left"
      = f.datetime_select :time, class: "form-right"
    div.field.form-group
      = f.label :status, class: "form-left"
      = f.select :status, [['Open', false], ['Closed', true]], class: "form-right"
    div.field.form-group
      = f.label :mainscore1, class: "form-left"
      = f.number_field :mainscore1, class: "form-right"
    div.field.form-group
      = f.label :mainscore2, class: "form-left"
      = f.number_field :mainscore2, class: "form-right"
    div.field.form-group
      = f.label :subscore1, class: "form-left"
      = f.number_field :subscore1, class: "form-right"
    div.field.form-group
      = f.label :subscore2, class: "form-left"
      = f.number_field :subscore2, class: "form-right"
    div.field.form-group
      = f.label :penscore1, class: "form-left"
      = f.number_field :penscore1, class: "form-right"
    div.field.form-group
      = f.label :penscore2, class: "form-left"
      = f.number_field :penscore2, class: "form-right"
    div.field.form-group
      = f.label :prior1, class: "form-left"
      = f.number_field :prior1, class: "form-right", step: 0.25
    div.field.form-group
      = f.label :prior2, class: "form-left"
      = f.number_field :prior2, class: "form-right", step: 0.25
    div.field.form-group
      = f.label :knockout, class: "form-left"
      = f.select :knockout, [['Group stage', false], ['Knockout stage', true]], class: "form-right"
    div.field.form-group
      = f.label :fee, class: "form-left"
      = f.number_field :fee, class: "form-right"
    div.field.form-group
      = f.label :special_final, class: "form-left"
      = f.check_box :special_final, class: "form-right"
    br
    div.field.form-group
      div.actions
        = f.submit 'Submit', class: "btn btn-primary form-left"

app/views/matches/edit.html.slim
h1 Editing Match

= render 'form'

div.col-xs-12
  hr
  = link_to 'Show', @match, class: "btn btn-primary"
  | |
  = link_to 'Back', matches_path(cup_id: @match.cup_id), class: "btn btn-primary"

app/views/matches/index.html.slim
.container
  h2 Listing Matches For #{@cup.name}

  div.panel.panel-default
    table.table.table-cond:wensed
      thead
        tr
          th.col-xs-1 #
          th.col-xs-3 Match
          th.col-xs-1 Time
          th.col-xs-1 Status
          th.col-xs-1 Score
          th.col-xs-1 Your Prediction
          th.col-xs-3 Prediction winner(s)
          th.col-xs-1 colspan="3"

  div.div-table-content
    table.table.table-hover.table-condensed
      tbody
        - @matches.each_with_index do |match, index|
          tr.clickable href="#{match_path(match)}"
            td.col-xs-1 = index+1
            td.col-xs-3 = render "shared/match_name", match: match
            td.col-xs-1 = match.time.to_s(:match)
            td.col-xs-1 = match.human_status
            td.col-xs-1 = match.fullscores
            - if match.prediction_of(@current_user)
              - if match.knockout?
                td.col-xs-1 = match.prediction_of(@current_user).winner_team.name
              - else
                td.col-xs-1 = match.prediction_of(@current_user).mainscores
            - else
              td.col-xs-1 Not available
            td.col-xs-3 = match.prediction_winners_names
            td.col-xs-1.text-right
              - if can?(:destroy, match)
                = link_to 'Destroy', delete_match_path(match), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger btn-one-col'
              - if can?(:edit, match)
                = link_to 'Edit', edit_match_path(match), class: 'btn btn-xs btn-warning btn-one-col btn-enabled'

  hr

  - if can?(:create, Match)
    = link_to 'New Match', new_match_path(cup_id: @cup.id), class: "btn btn-primary"

app/views/matches/new.html.slim
h1 New Match

= render 'form'

hr

div.col-xs-12
  hr
  = link_to 'Back', matches_path(cup_id: @cup.id), class: "btn btn-primary"

app/views/matches/show.html.slim
h2 Match information

table.table
  tr
    th.col-xs-4 Match
    th.col-xs-8 =render "shared/match_name", match: @match
  tr
    td Time
    td= @match.time.to_s(:match)
  tr
    td Stage
    td= @match.knockout? ? "Knockout" : "Group"
  - if @match.started?
    tr
      td Status
      td= @match.closed? ? "Finished" : "Started"
  tr
    td Fee
    td= @match.fee
  tr
    td Score
    td= @match.fullscores
  - if @match.prior1.present? || @match.prior2.present?
    tr
      td Bet priority
      td= @match.priorities
  tr
    td Number of Prediction(s)
    td= @match.predictions.count
  tr
    td Predictions winner(s)
    td= @match.prediction_winners_names

- @predictions = @match.started? ? @match.predictions : @match.predictions.where(user: current_user)
- if @predictions.count > 0
  h2 Predictions
  = render "shared/match_prediction", predictions: @predictions

hr

- @predictions = @match.predictions.where(user: current_user)
- if @predictions.count > 0
  - @prediction = @predictions.first
  - if can?(:edit, @prediction)
    = link_to 'Edit Prediction', edit_prediction_path(@prediction), class: "btn btn-primary"
    | |
- if @predictions.count == 0
  - if can?(:create, Prediction)
    = link_to 'New Prediction', new_prediction_path(cup_id: @match.cup_id), class: 'btn btn-primary'
    | |
- if can?(:create, Match)
  = link_to 'New Match', new_match_path(cup_id: @match.cup_id), class: "btn btn-primary"
  | |
- if can?(:edit, @match)
  = link_to 'Edit', edit_match_path(@match), class: "btn btn-primary"
  | |
= link_to 'Back', matches_path(cup_id: @match.cup_id), class: "btn btn-primary"